package MyApp.BE.enums;

public enum Regions {
    PRAHA,
    STREDOCESKY_KRAJ,
    JIHOCESKY_KRAJ,
    PLZENSKY_KRAJ,
    KARLOVARSKY_KRAJ,
    USTECKY_KRAJ,
    LIBERECKY_KRAJ,
    KRALOVEHRADECKY_KRAJ,
    PARDUBICKY_KRAJ,
    KRAJ_VYSOCINA,
    JIHOMORAVSKY_KRAJ,
    OLOMOUCKY_KRAJ,
    MORAVSKOSLEZSKY_KRAJ,
    ZLINSKY_KRAJ
}
